import pandas as pd

data = [
    {"question": "É normal ter dor no local da cirurgia?", "answer": "Sim, dor moderada é comum nos primeiros dias após a cirurgia. Se a dor for intensa ou piorar com o tempo, procure seu médico."},
    {"question": "Quando posso tomar banho normalmente?", "answer": "Normalmente, após 48 horas, mas siga as orientações do seu cirurgião. Evite molhar curativos até autorização."},
    {"question": "O que fazer se a ferida estiver vermelha ou inchada?", "answer": "Vermelhidão e inchaço leves são normais, mas se houver piora ou saída de pus, procure atendimento médico."},
    {"question": "Quanto tempo devo ficar em repouso?", "answer": "Depende do tipo de cirurgia; em geral, cirurgias pequenas exigem poucos dias, enquanto maiores podem exigir semanas."},
    {"question": "Posso dirigir depois da cirurgia?", "answer": "Você só deve dirigir quando estiver sem dor significativa e sem tomar medicamentos que causem sonolência."},
    {"question": "Quando posso voltar a trabalhar?", "answer": "Depende do tipo de cirurgia e do seu trabalho; consulte seu médico para uma liberação adequada."},
    {"question": "É normal ter febre após a cirurgia?", "answer": "Febre baixa (até 37,8°C) nas primeiras 48 horas pode ser normal. Febre alta ou persistente deve ser avaliada por um médico."},
    {"question": "Quando posso retomar exercícios físicos?", "answer": "Somente após liberação do cirurgião. Atividades leves podem ser liberadas em algumas semanas, dependendo do procedimento."},
    {"question": "O que fazer se sentir sangramento no local da cirurgia?", "answer": "Pequeno sangramento pode ocorrer, mas se for em grande quantidade ou contínuo, vá imediatamente ao hospital."},
    {"question": "Como saber se a ferida está infeccionada?", "answer": "Sinais como pus, dor intensa, mau cheiro, vermelhidão que piora ou febre alta indicam possível infecção."},
    {"question": "Preciso trocar o curativo em casa?", "answer": "Sim, mas siga rigorosamente as orientações do hospital. Mantenha as mãos limpas e use materiais estéreis."},
    {"question": "Posso comer normalmente após a cirurgia?", "answer": "Em cirurgias simples, sim; em cirurgias gastrointestinais, siga dieta orientada pelo médico."},
    {"question": "É seguro tomar meus medicamentos habituais?", "answer": "Informe seu médico sobre todos os remédios que usa. Alguns podem interferir na recuperação."},
    {"question": "Quanto tempo leva para os pontos serem retirados?", "answer": "Geralmente entre 7 e 14 dias, mas depende do local e tipo de cirurgia."},
    {"question": "O que fazer se sentir falta de ar ou dor no peito?", "answer": "Vá imediatamente ao pronto-socorro; esses sintomas podem indicar complicações graves, como trombose ou embolia."},
    {"question": "Quando posso apoiar o pé no chão após uma cirurgia no joelho?", "answer": "Depende da cirurgia. Em algumas, você pode apoiar imediatamente; em outras, precisa esperar liberação médica."},
    {"question": "É normal o joelho ficar inchado após a cirurgia?", "answer": "Sim, inchaço é comum nas primeiras semanas. Mantenha a perna elevada e aplique gelo conforme orientação médica."},
    {"question": "Quando posso dirigir após uma artroscopia no joelho?", "answer": "Normalmente em 2 a 4 semanas, mas só com liberação do médico e se conseguir movimentar a perna com segurança."},
    {"question": "Quanto tempo devo usar muletas após cirurgia no joelho?", "answer": "Geralmente entre 2 a 6 semanas, dependendo do procedimento e da recuperação."},
    {"question": "É normal ter gases ou prisão de ventre após cirurgia abdominal?", "answer": "Sim, o intestino pode ficar lento. Caminhar ajuda. Se durar mais de 4 dias, procure seu médico."},
    {"question": "Quando posso dirigir após cirurgia na barriga?", "answer": "Quando conseguir se movimentar sem dor e sem tomar remédios que causem sonolência, geralmente após 2-4 semanas."},
    {"question": "Posso dormir de lado depois de uma cirurgia abdominal?", "answer": "Se sentir conforto e sem dor, sim. Use travesseiros para apoio se necessário."},
    {"question": "O que fazer se notar vermelhidão ao redor do corte na barriga?", "answer": "Se for leve, observe. Se aumentar ou houver saída de pus, procure seu médico imediatamente."},
    {"question": "É normal ter inchaço no rosto após remover o siso?", "answer": "Sim, o inchaço atinge o pico em 48h e começa a melhorar depois. Aplicar gelo ajuda."},
    {"question": "Quanto tempo devo ficar sem comer alimentos sólidos após retirar o siso?", "answer": "Alimente-se com líquidos e pastosos nas primeiras 24-48h; depois, introduza sólidos conforme tolerância."},
    {"question": "Posso escovar os dentes normalmente após extração do siso?", "answer": "Escove com cuidado, evitando o local da cirurgia no primeiro dia. Retome a higiene normal aos poucos, conforme orientação."},
    {"question": "O que fazer se sangrar muito após remover o siso?", "answer": "Morda uma gaze limpa por 30 minutos. Se o sangramento continuar intenso, procure o dentista ou serviço de urgência."},
    {"question": "Quando posso praticar exercícios físicos após extração do siso?", "answer": "Evite exercícios por pelo menos 3 dias, pois podem aumentar o sangramento. Retorne com liberação do dentista."},
    {"question": "É normal ter visão embaçada após cirurgia no olho?", "answer": "Sim, a visão pode ficar embaçada por alguns dias ou semanas. Se piorar ou vier com dor intensa, procure seu médico."},
    {"question": "Quando posso voltar a dirigir após cirurgia ocular?", "answer": "Apenas quando sua visão estiver clara e você se sentir seguro. Seu oftalmologista deve liberar a direção, geralmente após alguns dias ou semanas."},
    {"question": "Posso coçar o olho depois da cirurgia?", "answer": "Não! Evite coçar ou esfregar os olhos para não prejudicar a cicatrização."},
    {"question": "Quando posso usar maquiagem nos olhos após a cirurgia?", "answer": "Geralmente após 2 a 4 semanas, mas confirme com seu oftalmologista."},
    {"question": "O que fazer se sentir dor intensa ou notar secreção após a cirurgia?", "answer": "Procure seu oftalmologista imediatamente; isso pode indicar infecção ou outra complicação."},
    {"question": "Quando posso retomar exercícios físicos após cirurgia ocular?", "answer": "Em geral, exercícios leves podem ser retomados em 1 semana, mas evite atividades que causem impacto ou risco de trauma ocular por pelo menos 2 a 4 semanas."},
    {"question": "É normal ter sensibilidade à luz após cirurgia no olho?", "answer": "Sim, fotofobia é comum nos primeiros dias. Use óculos escuros e siga as orientações médicas."},
    {"question": "Posso tomar banho de sol após a cirurgia?", "answer": "Evite exposição direta ao sol sobre a cicatriz por pelo menos 30 dias para prevenir manchas e melhorar a cicatrização."},
    {"question": "Quando posso ter alta após a cirurgia?", "answer": "Depende do procedimento. Cirurgias simples permitem alta no mesmo dia ou no dia seguinte, mas cirurgias mais complexas podem exigir internação prolongada."},
    {"question": "É normal ter alteração de humor ou sentir-se deprimido após cirurgia?", "answer": "Sim, alterações emocionais podem ocorrer no pós-operatório devido a fatores como dor, anestesia ou mudanças na rotina."},
    {"question": "Posso beber refrigerante ou bebidas gaseificadas após a cirurgia?", "answer": "Evite nas primeiras semanas, principalmente em cirurgias gastrointestinais, pois podem causar desconforto abdominal."},
    {"question": "Quando posso retomar relações sexuais após cirurgia?", "answer": "Depende do procedimento e do conforto. Para cirurgias abdominais ou ortopédicas, geralmente entre 4 a 6 semanas; confirme com seu médico."},
     {"question": "Quando posso dormir de lado após uma cirurgia plástica?", "answer": "Geralmente após 2 a 4 semanas, mas siga as orientações do cirurgião para não prejudicar a cicatrização."},
    {"question": "É normal sentir dormência em áreas operadas na cirurgia plástica?", "answer": "Sim, alterações de sensibilidade podem ocorrer e costumam melhorar com o tempo, mas informe seu médico se durar muito."},
    {"question": "Quando posso fazer drenagem linfática após cirurgia plástica?", "answer": "Normalmente a partir do 3º ao 5º dia pós-operatório, mas apenas com liberação médica."},
    {"question": "O que fazer se perceber seroma após cirurgia plástica?", "answer": "Seroma (acúmulo de líquido) pode ocorrer; informe seu médico para avaliação e possível drenagem."},
     {"question": "É normal sentir cansaço após cirurgia cardíaca?", "answer": "Sim, o cansaço é comum. O retorno às atividades deve ser gradual, seguindo as orientações do cardiologista."},
    {"question": "Quando posso voltar a subir escadas após cirurgia cardíaca?", "answer": "Com liberação médica, geralmente a partir de 2 a 4 semanas, mas suba devagar e com apoio se necessário."},
    {"question": "Quando posso ter alta após cirurgia de ponte de safena?", "answer": "A alta hospitalar costuma ocorrer entre 5 a 10 dias, dependendo da evolução e ausência de complicações."},
    {"question": "Posso tomar anti-inflamatório após cirurgia ortopédica?", "answer": "Somente se for prescrito pelo seu médico, pois alguns anti-inflamatórios podem prejudicar a cicatrização óssea."},
    {"question": "É normal sentir formigamento após cirurgia ortopédica?", "answer": "Sim, pode ocorrer por manipulação dos nervos. Se persistir ou piorar, informe seu médico."},
    {"question": "Quando posso colocar peso na perna após cirurgia de fratura?", "answer": "Apenas quando liberado pelo ortopedista, pois apoiar antes do tempo pode prejudicar a consolidação do osso."},
    {"question": "Quando posso ter relações sexuais após cirurgia ginecológica?", "answer": "Geralmente de 6 a 8 semanas após a cirurgia, mas confirme com seu ginecologista."},
    {"question": "É normal ter corrimento após cirurgia ginecológica?", "answer": "Corrimento leve pode ser normal, mas se tiver odor forte ou cor anormal, procure o médico."},
    {"question": "Quando posso retomar atividades físicas após histerectomia?", "answer": "Atividades leves podem ser retomadas em 4 semanas; exercícios mais intensos só com liberação médica."},


]

df = pd.DataFrame(data)
df.to_csv("custom_postoperative_faq.csv", index=False)
